config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORY, message: "%{value} is not included in the list" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (0..5) }, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Reviews.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <!--  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> All your favorite restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant|%>
    <li><%= link_to restaurant.name, restaurant_path(restaurant)%></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1> Create your restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/show.html.erb
<div class = "container">
  <div>
    <h1><%= @restaurant.name %></h1>
    <h2><%= @restaurant.category %></h2>
    <h2><%= @restaurant.address %></h2>
    <h2><%= @restaurant.phone_number %></h2>
  </div>

<div class = reviews >
  <h2> Reviews : </h2>
  <ul>
    <%  @restaurant.reviews.each do |review|%>
      <li><%= review.content%></li>
    <% end %>
  </ul>
</div>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
<%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/reviews/new.html.erb
<h1> Add review </h1>

<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit",class: "btn btn-primary"%>
<% end %>